version: '3.8'

services:
  bus-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bus-monitor-app
    restart: unless-stopped
    volumes:
      - ./classified:/app/classified
      - ./detections:/app/detections
      - ./.env:/app/.env:ro
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"